version: '2'
services:
    webchat-app:
        image: webchat
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATASOURCE_URL=jdbc:postgresql://webchat-postgresql:5432/webchat
            - SPRING_REDIS_HOST=webchat-redis
        ports:
            - 8080:8080
    webchat-postgresql:
        extends:
            file: postgresql.yml
            service: webchat-postgresql
    webchat-redis:
            extends:
                file: redis.yml
                service: webchat-redis

